/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pokemonneatbens;

/**
 *
 * @author aditya wirz
 */
public class ChestItemPokemonGUI extends javax.swing.JFrame {
    public Dunia dunia;
    public Player player;

    public ChestItemPokemonGUI(){
        initComponents();
    }
    /**
     * Creates new form UsserInterface
     */
    public ChestItemPokemonGUI(Dunia dunia, Player player) {
        //test1
        initComponents();
        this.dunia = dunia;
        this.player = player;
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ToUsserIn7 = new javax.swing.JButton();
        ToUsserIn8 = new javax.swing.JButton();
        ToUsserIn9 = new javax.swing.JButton();
        ToUsserIn10 = new javax.swing.JButton();
        ToUsserIn11 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ToUsserIn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/ItemWaktuPerang/3.png"))); // NOI18N
        ToUsserIn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToUsserIn7ActionPerformed(evt);
            }
        });
        getContentPane().add(ToUsserIn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 770, 290, 70));

        ToUsserIn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/ItemWaktuPerang/4.png"))); // NOI18N
        ToUsserIn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToUsserIn8ActionPerformed(evt);
            }
        });
        getContentPane().add(ToUsserIn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 870, 350, 90));

        ToUsserIn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/ItemWaktuPerang/5.png"))); // NOI18N
        ToUsserIn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToUsserIn9ActionPerformed(evt);
            }
        });
        getContentPane().add(ToUsserIn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 870, 350, 90));

        ToUsserIn10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/ItemWaktuPerang/1.png"))); // NOI18N
        ToUsserIn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToUsserIn10ActionPerformed(evt);
            }
        });
        getContentPane().add(ToUsserIn10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 770, 290, 70));

        ToUsserIn11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/ItemWaktuPerang/2.png"))); // NOI18N
        ToUsserIn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToUsserIn11ActionPerformed(evt);
            }
        });
        getContentPane().add(ToUsserIn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 770, 290, 70));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama", "Element", "Level"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 720, 590));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 100)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/ItemWaktuPerang/NEW GAME (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ToUsserIn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToUsserIn7ActionPerformed
        // TODO add your handling code here:
        HomeBaseGUI rumah = new HomeBaseGUI(dunia, player);
        setVisible(false);
        rumah.setVisible(true);
    }//GEN-LAST:event_ToUsserIn7ActionPerformed

    private void ToUsserIn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToUsserIn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToUsserIn8ActionPerformed

    private void ToUsserIn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToUsserIn9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToUsserIn9ActionPerformed

    private void ToUsserIn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToUsserIn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToUsserIn10ActionPerformed

    private void ToUsserIn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToUsserIn11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToUsserIn11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChestItemPokemonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChestItemPokemonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChestItemPokemonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChestItemPokemonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        ChestItemPokemonGUI Interface = new ChestItemPokemonGUI();
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChestItemPokemonGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ToUsserIn10;
    private javax.swing.JButton ToUsserIn11;
    private javax.swing.JButton ToUsserIn7;
    private javax.swing.JButton ToUsserIn8;
    private javax.swing.JButton ToUsserIn9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
