/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pokemonneatbens;

import javax.swing.JLabel;

/**
 *
 * @author aditya wirz
 */
public class EvolveGUI extends javax.swing.JFrame {

    public Player player;
    public Dunia dunia;
    public Monster monster;
    public String nama;
    /**
     * Creates new form UsserInterface
     */
    public EvolveGUI() {
        initComponents();
    }
    
    public EvolveGUI(Player player, Dunia dunia) {
        this.player = player;
        initComponents();
        this.dunia = dunia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ToUsserIn1 = new javax.swing.JButton();
        ToUsserIn2 = new javax.swing.JButton();
        ToUsserIn3 = new javax.swing.JButton();
        ToUsserIn4 = new javax.swing.JButton();
        ToUsserIn5 = new javax.swing.JButton();
        ToUsserIn6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ToUsserIn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/Evolve/Back.png"))); // NOI18N
        ToUsserIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToUsserIn1ActionPerformed(evt);
            }
        });
        getContentPane().add(ToUsserIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 870, 350, 90));

        ToUsserIn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/Evolve/1.png"))); // NOI18N
        ToUsserIn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToUsserIn2ActionPerformed(evt);
            }
        });
        getContentPane().add(ToUsserIn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 280, 60));

        ToUsserIn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/Evolve/1.png"))); // NOI18N
        ToUsserIn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToUsserIn3ActionPerformed(evt);
            }
        });
        getContentPane().add(ToUsserIn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 280, 60));

        ToUsserIn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/Evolve/1.png"))); // NOI18N
        ToUsserIn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToUsserIn4ActionPerformed(evt);
            }
        });
        getContentPane().add(ToUsserIn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 280, 60));

        ToUsserIn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/Evolve/NEW GAME (4).png"))); // NOI18N
        ToUsserIn5.setVisible(false);
        ToUsserIn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToUsserIn5ActionPerformed(evt);
            }
        });
        getContentPane().add(ToUsserIn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 280, 60));

        ToUsserIn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/Evolve/NEW GAME (4).png"))); // NOI18N
        ToUsserIn6.setVisible(false);
        ToUsserIn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToUsserIn6ActionPerformed(evt);
            }
        });
        getContentPane().add(ToUsserIn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 280, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        if (player.playerMonster.size() > 1) {
            nama = player.playerMonster.get(1).name;
            jLabel2.setText(nama);
        }else{
            jLabel2.setText("KOSONG");
        }
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 140, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        if (player.playerMonster.size() > 2) {
            nama = player.playerMonster.get(2).name;
            jLabel3.setText(nama);
        }else{
            jLabel3.setText("KOSONG");
        }
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, 140, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 730, 310, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        nama = player.playerMonster.get(0).name;
        jLabel5.setText(nama);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 140, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 140, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 140, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/Evolve/41.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ToUsserIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToUsserIn1ActionPerformed
        dunia = new HomeBase(dunia.monsterChest);
        HomeBaseGUI rumah = new HomeBaseGUI(dunia,player);
        setVisible(false);
        rumah.setVisible(true);
    }//GEN-LAST:event_ToUsserIn1ActionPerformed

    private void ToUsserIn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToUsserIn2ActionPerformed
        if (player.playerMonster.size() > 2) {
            monster = player.playerMonster.get(2);
            if (monster.evolved) {
                jLabel4.setText("Monster Sudah Evolve di Level Ini!");
            }else{
                jLabel4.setText("");
                switch (monster.element) {
                    case FIRE:
                        ToUsserIn5.setVisible(true);
                        ToUsserIn6.setVisible(true);
                        jLabel6.setText("WIND");
                        jLabel7.setText("EARTH");
                        break;
                    case WATER:
                        ToUsserIn5.setVisible(true);
                        ToUsserIn6.setVisible(true);
                        jLabel6.setText("WIND");
                        jLabel7.setText("ICE");
                        break;
                    case WIND:
                        ToUsserIn5.setVisible(true);
                        ToUsserIn6.setVisible(true);
                        jLabel6.setText("FIRE");
                        jLabel7.setText("WATER");
                        break;
                    case ICE:
                        ToUsserIn5.setVisible(true);
                        ToUsserIn6.setVisible(true);
                        jLabel6.setText("EARTH");
                        jLabel7.setText("WATER");
                        break;
                    case EARTH:
                        ToUsserIn5.setVisible(true);
                        ToUsserIn6.setVisible(true);
                        jLabel6.setText("FIRE");
                        jLabel7.setText("ICE");
                        break;
                    default:
                        break;
                }
            }
        }else{
            jLabel4.setText("TIDAK ADA MONSTER");
        }
    }//GEN-LAST:event_ToUsserIn2ActionPerformed

    private void ToUsserIn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToUsserIn3ActionPerformed
        monster = player.playerMonster.get(0);
        if (monster.evolved) {
            jLabel4.setText("Monster Sudah Evolve di Level Ini!");
        }else{
            jLabel4.setText("");
            switch (monster.element) {
                case FIRE:
                    ToUsserIn5.setVisible(true);
                    ToUsserIn6.setVisible(true);
                    jLabel6.setText("WIND");
                    jLabel7.setText("EARTH");
                    break;
                case WATER:
                    ToUsserIn5.setVisible(true);
                    ToUsserIn6.setVisible(true);
                    jLabel6.setText("WIND");
                    jLabel7.setText("ICE");
                    break;
                case WIND:
                    ToUsserIn5.setVisible(true);
                    ToUsserIn6.setVisible(true);
                    jLabel6.setText("FIRE");
                    jLabel7.setText("WATER");
                    break;
                case ICE:
                    ToUsserIn5.setVisible(true);
                    ToUsserIn6.setVisible(true);
                    jLabel6.setText("EARTH");
                    jLabel7.setText("WATER");
                    break;
                case EARTH:
                    ToUsserIn5.setVisible(true);
                    ToUsserIn6.setVisible(true);
                    jLabel6.setText("FIRE");
                    jLabel7.setText("ICE");
                    break;
                default:
                    break;
            }
        }
        
    }//GEN-LAST:event_ToUsserIn3ActionPerformed

    private void ToUsserIn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToUsserIn4ActionPerformed
        if (player.playerMonster.size() > 1) {
            monster = player.playerMonster.get(1);
            if (monster.evolved) {
                jLabel4.setText("Monster Sudah Evolve di Level Ini!");
            }else{
                jLabel4.setText("");
                switch (monster.element) {
                    case FIRE:
                        ToUsserIn5.setVisible(true);
                        ToUsserIn6.setVisible(true);
                        jLabel6.setText("WIND");
                        jLabel7.setText("EARTH");
                        break;
                    case WATER:
                        ToUsserIn5.setVisible(true);
                        ToUsserIn6.setVisible(true);
                        jLabel6.setText("WIND");
                        jLabel7.setText("ICE");
                        break;
                    case WIND:
                        ToUsserIn5.setVisible(true);
                        ToUsserIn6.setVisible(true);
                        jLabel6.setText("FIRE");
                        jLabel7.setText("WATER");
                        break;
                    case ICE:
                        ToUsserIn5.setVisible(true);
                        ToUsserIn6.setVisible(true);
                        jLabel6.setText("EARTH");
                        jLabel7.setText("WATER");
                        break;
                    case EARTH:
                        ToUsserIn5.setVisible(true);
                        ToUsserIn6.setVisible(true);
                        jLabel6.setText("FIRE");
                        jLabel7.setText("ICE");
                        break;
                    default:
                        break;
                }
            }
        }else{
            jLabel4.setText("TIDAK ADA MONSTER!");
        }
    }//GEN-LAST:event_ToUsserIn4ActionPerformed

    private void ToUsserIn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToUsserIn5ActionPerformed
        int index = player.playerMonster.indexOf(monster);
        if (monster.evolved) {
            jLabel4.setText("MONSTER SUDAH EVOLVE DI LEVEL INI");
        }else{
            switch (jLabel6.getText()) {
                case "FIRE":
                    monster = new FireMonster(monster.name, monster.level, monster.maxHp, monster.hp, monster.ep);
                    break;
                case "WIND":
                    monster = new WindMonster(monster.name, monster.level, monster.maxHp, monster.hp, monster.ep);
                    break;
                case "WATER":
                    monster = new WaterMonster(monster.name, monster.level, monster.maxHp, monster.hp, monster.ep);
                    break;
                case "ICE":
                    monster = new IceMonster(monster.name, monster.level, monster.maxHp, monster.hp, monster.ep);
                    break;
                case "EARTH":
                    monster = new EarthMonster(monster.name, monster.level, monster.maxHp, monster.hp, monster.ep);
                    break;
                default:
                    jLabel4.setText("Error");
                    break;
            }
            monster.evolved = true;
            player.playerMonster.add(index, monster);
            player.playerMonster.remove(index + 1);
            jLabel4.setText("BERHASIL EVOLVE!");

        }
    }//GEN-LAST:event_ToUsserIn5ActionPerformed

    private void ToUsserIn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToUsserIn6ActionPerformed
        int index = player.playerMonster.indexOf(monster);
        if (monster.evolved) {
            jLabel4.setText("MONSTER SUDAH EVOLVE DI LEVEL INI");
        }else{
            switch (jLabel6.getText()) {
                case "FIRE":
                    monster = new FireMonster(monster.name, monster.level, monster.maxHp, monster.hp, monster.ep);
                    break;
                case "WIND":
                    monster = new WindMonster(monster.name, monster.level, monster.maxHp, monster.hp, monster.ep);
                    break;
                case "WATER":
                    monster = new WaterMonster(monster.name, monster.level, monster.maxHp, monster.hp, monster.ep);
                    break;
                case "ICE":
                    monster = new IceMonster(monster.name, monster.level, monster.maxHp, monster.hp, monster.ep);
                    break;
                case "EARTH":
                    monster = new EarthMonster(monster.name, monster.level, monster.maxHp, monster.hp, monster.ep);
                    break;
                default:
                    jLabel4.setText("Error");
                    break;
            }
            monster.evolved = true;
            player.playerMonster.add(index, monster);
            player.playerMonster.remove(index + 1);
            jLabel4.setText("BERHASIL EVOLVE!");

        }

    }//GEN-LAST:event_ToUsserIn6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EvolveGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EvolveGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EvolveGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EvolveGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        EvolveGUI Interface = new EvolveGUI();
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EvolveGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ToUsserIn1;
    private javax.swing.JButton ToUsserIn2;
    private javax.swing.JButton ToUsserIn3;
    private javax.swing.JButton ToUsserIn4;
    private javax.swing.JButton ToUsserIn5;
    private javax.swing.JButton ToUsserIn6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
