/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pokemonneatbens;

import java.awt.Color;
import java.util.ArrayList;

import javax.swing.ImageIcon;

/**
 *
 * @author aditya wirz
 */
public class IsiNamaGui extends javax.swing.JFrame {
    public Player player;
    public Dunia dunia;
    Monster monster = null;
    ImageIcon Agoni = new ImageIcon("Agoni.png");
    ImageIcon Trachy = new ImageIcon("Trachy.png");
    ImageIcon Fotia = new ImageIcon("Fotia.png");
    ImageIcon Megali = new ImageIcon("Megali.png");
    ImageIcon Krya = new ImageIcon("Krya.png");
    ImageIcon Pagomenos = new ImageIcon("Pagomenos.png");
    ImageIcon Naida = new ImageIcon("Naida.png");
    ImageIcon Irupe = new ImageIcon("Irupe.png");
    ImageIcon Anemos = new ImageIcon("Anemos.png");
    ImageIcon Ishchyroi = new ImageIcon("Ishchyroi.png");
    /**
     * Creates new form UsserInterface
     */
    public IsiNamaGui(Player player, Dunia dunia) {
        this.player = player;
        this.dunia = dunia;
        initComponents();
    }
    public IsiNamaGui(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/IsiNama/NEW GAME (2).png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 790, 350, 80));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/IsiNama/Start.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 790, 350, 80));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/New folder/2.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, 350, 80));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/New folder/3.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 670, 350, 80));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/New folder/1.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 350, 80));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 340, 70));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 230, 190));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 330, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/IsiNama/_d5c0ef46-65ee-4203-80fd-e1ad2ae962d7.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        UsserInterface balik = new UsserInterface();
        setVisible(false);
        balik.setVisible(true);
        //gacor gacor
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        //Start
        jLabel3.setForeground(Color.RED);
        if(jTextField1.getText().isEmpty() && monster == null){
            jLabel3.setText("Nama Kosong!!! Monster Kosong!!!");
        }
        else if(jTextField1.getText().isEmpty()){
            jLabel3.setText("Nama Kosong!!!");
        }
        else if(monster == null){
            jLabel3.setText("Pilih Monster!!!");
        }else{
            player = new Player(jTextField1.getText(), new ArrayList<>(), new ArrayList<>(), new ArrayList<>(), new ArrayList<>());
            player.playerMonster.add(monster);
            player.money = 100;
            HomeBaseGUI rumah =  new HomeBaseGUI(dunia, player);
            setVisible(false);
            rumah.setVisible(true);
        }    
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        // Naida
        monster = WaterMonster.WaterMonsterCollection(0, 1);
        jLabel2.setIcon(Naida);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        // Anemos
        monster = WindMonster.WindMonsterCollection(0, 1);
        jLabel2.setIcon(Anemos);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        //Megali
        monster = FireMonster.FireMonsterCollection(1, 1);
        jLabel2.setIcon(Megali);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IsiNamaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IsiNamaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IsiNamaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IsiNamaGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        IsiNamaGui Interface = new IsiNamaGui();
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IsiNamaGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
