/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pokemonneatbens;

/**
 *
 * @author aditya wirz
 */
public class LoadGame extends javax.swing.JFrame {
    public Player player;
    public Monster monster;
    public Dunia dunia;
    public int index;
    public Monster wild;
    /**
     * Creates new form UsserInterface
     */
    public LoadGame() {
        initComponents();
    }

    public LoadGame(Player player, Monster monster, Dunia dunia, int index, Monster wild) {
        this.player = player;
        this.monster = monster;
        this.dunia = dunia;
        this.index = index;
        this.wild = wild;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ToUsserIn3 = new javax.swing.JButton();
        ToUsserIn2 = new javax.swing.JButton();
        ToUsserIn1 = new javax.swing.JButton();
        ToUsserIn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ToUsserIn4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText(Integer.toString(player.health.size()));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 270, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText(Integer.toString(player.courage.size()));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 270, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setText(Integer.toString(player.okeball.size()));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 600, 270, 50));

        ToUsserIn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/ItemDungeon/1.png"))); // NOI18N
        ToUsserIn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToUsserIn3ActionPerformed(evt);
            }
        });
        getContentPane().add(ToUsserIn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 310, 70));

        ToUsserIn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/ItemDungeon/1.png"))); // NOI18N
        ToUsserIn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToUsserIn2ActionPerformed(evt);
            }
        });
        getContentPane().add(ToUsserIn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 310, 70));

        ToUsserIn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/ItemDungeon/1.png"))); // NOI18N
        ToUsserIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToUsserIn1ActionPerformed(evt);
            }
        });
        getContentPane().add(ToUsserIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 660, 310, 70));

        ToUsserIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/MenuBack.png"))); // NOI18N
        ToUsserIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToUsserInActionPerformed(evt);
            }
        });
        getContentPane().add(ToUsserIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 890, 170, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/ItemDungeon/19.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 1000));

        ToUsserIn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/ItemDungeon/1.png"))); // NOI18N
        ToUsserIn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToUsserIn4ActionPerformed(evt);
            }
        });
        getContentPane().add(ToUsserIn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 310, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ToUsserInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToUsserInActionPerformed
        TempatWar war = new TempatWar(player,dunia,index);
        war.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ToUsserInActionPerformed

    private void ToUsserIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToUsserIn1ActionPerformed
        if (player.okeball.size() != 0) {
            if ((wild.hp / wild.maxHp) * 100 < 25) {
                wild.ketangkap = true;
            }
        }

        if (wild.ketangkap) {
            dunia.monsterChest.add(wild);
            BerhasilTangkapMonsterGui tangkap = new BerhasilTangkapMonsterGui(dunia, player);
            tangkap.setVisible(true);
        }
        player.okeball.remove(0);
        setVisible(false);
    }//GEN-LAST:event_ToUsserIn1ActionPerformed

    private void ToUsserIn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToUsserIn2ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_ToUsserIn2ActionPerformed

    private void ToUsserIn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToUsserIn3ActionPerformed
        if (player.health.size() != 0) {
            player.playerMonster.get(index).hp += 100;
            if (player.playerMonster.get(index).hp > player.playerMonster.get(index).maxHp) {
                player.playerMonster.get(index).hp = player.playerMonster.get(index).maxHp;
            }
            player.health.remove(0);
        }

        System.out.println("Berhasil menggunakan health");
        setVisible(false);
    }//GEN-LAST:event_ToUsserIn3ActionPerformed

    private void ToUsserIn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToUsserIn4ActionPerformed
        if (player.courage.size() != 0) {
            player.playerMonster.get(index).boosted = true;
            player.courage.remove(0);
            setVisible(false);
        }
    }//GEN-LAST:event_ToUsserIn4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        LoadGame Interface = new LoadGame();
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ToUsserIn;
    private javax.swing.JButton ToUsserIn1;
    private javax.swing.JButton ToUsserIn2;
    private javax.swing.JButton ToUsserIn3;
    private javax.swing.JButton ToUsserIn4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
