/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pokemonneatbens;

/**
 *
 * @author aditya wirz
 */
public class SHOPGUI extends javax.swing.JFrame {

    /**
     * Creates new form UsserInterface
     */
    public SHOPGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ToUsserIn2 = new javax.swing.JButton();
        ToUsserIn8 = new javax.swing.JButton();
        ToUsserIn9 = new javax.swing.JButton();
        ToUsserIn7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ToUsserIn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/Shop/attackpotion.png"))); // NOI18N
        ToUsserIn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToUsserIn2ActionPerformed(evt);
            }
        });
        getContentPane().add(ToUsserIn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 190, 50));

        ToUsserIn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/Shop/okeball.png"))); // NOI18N
        ToUsserIn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToUsserIn8ActionPerformed(evt);
            }
        });
        getContentPane().add(ToUsserIn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 460, 190, 50));

        ToUsserIn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/Shop/healthpotion.png"))); // NOI18N
        ToUsserIn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToUsserIn9ActionPerformed(evt);
            }
        });
        getContentPane().add(ToUsserIn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 190, 50));

        ToUsserIn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/Dungeon/NEW GAME (1)/backhomebase.png"))); // NOI18N
        ToUsserIn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToUsserIn7ActionPerformed(evt);
            }
        });
        getContentPane().add(ToUsserIn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 900, 270, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SRC/Shop/Shop.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ToUsserIn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToUsserIn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToUsserIn2ActionPerformed

    private void ToUsserIn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToUsserIn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToUsserIn7ActionPerformed

    private void ToUsserIn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToUsserIn8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToUsserIn8ActionPerformed

    private void ToUsserIn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToUsserIn9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToUsserIn9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SHOPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SHOPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SHOPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SHOPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        SHOPGUI Interface = new SHOPGUI();
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SHOPGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ToUsserIn2;
    private javax.swing.JButton ToUsserIn7;
    private javax.swing.JButton ToUsserIn8;
    private javax.swing.JButton ToUsserIn9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
